export default function PrivacyPolicy() {
  return <main className="privacy-page">
    <header className="privacy-header"><a className="privacy-back" href="/">← Voltar ao portfólio</a><p className="eyebrow">Deva Braga / documento legal</p><h1>Política de<br /><em>Privacidade.</em></h1><p className="privacy-lead">Esta política explica, de forma transparente, quais dados podem ser tratados quando você navega pelo portfólio, solicita um orçamento ou interage com seus recursos.</p><p className="privacy-updated">Última atualização: 16 de setembro de 2026</p></header>
    <div className="privacy-body">
      <section><span className="section-index">01</span><div><h2>Quem controla os dados</h2><p>O controlador dos dados tratados neste site é Deva Braga, profissional independente responsável pelo portfólio. Para dúvidas, solicitações ou exercício de direitos, entre em contato pelo endereço <a href="mailto:oi@devabraga.com">oi@devabraga.com</a>.</p></div></section>
      <section><span className="section-index">02</span><div><h2>Quais dados são coletados</h2><p><strong>Pedido de orçamento:</strong> nome, e-mail, WhatsApp opcional e a mensagem enviada. Esses dados são fornecidos voluntariamente e tratados para responder ao contato e avaliar o projeto solicitado.</p><p><strong>Analytics:</strong> após o aceite de cookies, o site registra eventos agregados de visualização de página, abertura de projeto e clique em links externos. O identificador de visitante é técnico e aleatório; o site não registra endereço IP por meio do recurso de analytics implementado.</p><p><strong>Área administrativa:</strong> dados básicos de autenticação podem ser tratados para permitir o acesso autorizado ao painel privado. Visitantes não precisam criar conta para navegar, filtrar trabalhos ou solicitar orçamento.</p></div></section>
      <section><span className="section-index">03</span><div><h2>Cookies e consentimento</h2><p>O site utiliza um cookie/local storage técnico para lembrar se você aceitou ou recusou o aviso de cookies. O analytics só é ativado depois de uma ação afirmativa de aceite. Ao recusar, o site mantém o funcionamento essencial e não registra eventos de tráfego.</p><p>Você pode apagar os dados locais do navegador a qualquer momento. Isso fará o aviso aparecer novamente para que uma nova escolha seja feita.</p></div></section>
      <section><span className="section-index">04</span><div><h2>Finalidades e bases legais</h2><p>Os dados de orçamento são tratados para executar medidas solicitadas por você antes de uma eventual contratação e para responder à sua mensagem. O registro de analytics depende do seu consentimento, que pode ser recusado sem impedir o acesso ao portfólio. O acesso administrativo é tratado para segurança e gestão do serviço.</p></div></section>
      <section><span className="section-index">05</span><div><h2>Armazenamento e compartilhamento</h2><p>Pedidos de orçamento e eventos consentidos são armazenados na infraestrutura de banco de dados do projeto. O conteúdo do pedido pode ser acessado pelo responsável pelo portfólio e por prestadores técnicos necessários para hospedar, proteger e operar o site. Não vendemos dados pessoais nem os usamos para publicidade comportamental.</p><p>Os dados são mantidos pelo tempo necessário para responder ao pedido, administrar a relação profissional, cumprir obrigações legais ou preservar registros de segurança. Quando não forem mais necessários, serão eliminados ou anonimizados de forma razoável.</p></div></section>
      <section><span className="section-index">06</span><div><h2>Seus direitos</h2><p>Nos termos da legislação aplicável, incluindo a LGPD quando aplicável, você pode solicitar confirmação da existência de tratamento, acesso, correção, anonimização, eliminação, portabilidade quando cabível, informação sobre compartilhamentos e revogação do consentimento. Envie a solicitação para <a href="mailto:oi@devabraga.com">oi@devabraga.com</a>. Podemos pedir informações mínimas para confirmar a identidade e evitar solicitações indevidas.</p></div></section>
      <section><span className="section-index">07</span><div><h2>Segurança e atualizações</h2><p>Adotamos medidas técnicas e organizacionais compatíveis com o porte e a finalidade do site, incluindo autenticação para o painel e minimização de dados. Nenhum serviço conectado à internet é totalmente livre de riscos; se identificarmos um incidente relevante, tomaremos as medidas cabíveis e atualizaremos esta política quando houver mudança material no tratamento.</p></div></section>
      <section><span className="section-index">08</span><div><h2>Contato</h2><p>Para dúvidas sobre privacidade, cookies ou pedidos de orçamento, escreva para <a href="mailto:oi@devabraga.com">oi@devabraga.com</a>. Para conhecer novos trabalhos, visite também <a href="https://www.behance.net/deva_braga" target="_blank" rel="noreferrer">MEU BEHANCE</a>.</p></div></section>
    </div>
    <footer className="privacy-footer"><a href="/">Deva Braga</a><span>Salvador, BR · 2026</span></footer>
  </main>;
}
